name: Java CI with Maven

on:
  push:
    branches: [ "main","releases/*"]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**.md" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: install
        run: mvn -B install --file pom.xml
      - name: test
        run: mvn -B test --file pom.xml